### PR TITLE
PHP8.4 deprecation notices fix attempt

### PR DESCRIPTION
**Pull request by NielBuys**
Attempt to Fix below issues
https://github.com/bcit-ci/CodeIgniter/issues/6302
https://github.com/bcit-ci/CodeIgniter/issues/6300
https://github.com/bcit-ci/CodeIgniter/issues/6300

### CODE REVIEW

**Comment by NielBuys** [comment]
Changes not tested on php8.4 yet. But it should remove notices. Changes works on my php8.3 environment.

**Comment by jamieburchell** [comment]
Should probably bump the required PHP version to 7.1 if using nullable types. I personally don't care about anything < PHP 8.2, but I'm not sure if these PRs are supposed to be compatible with the PHP version mentioned in composer.json.

**Comment by jamieburchell** [comment]
Won't there still be deprecation notices in PHP 8.4 because `session.sid_length` is still being used?

**Comment by NielBuys** [comment]
> Should probably bump the required PHP version to 7.1 if using nullable types. I personally don't care about anything < PHP 8.2, but I'm not sure if these PRs are supposed to be compatible with the PHP version mentioned in composer.json.

On my fork I have bumped the minimum php version to 7.4. That's the reason I have not pushed this pull request to the main repository.

**Comment by NielBuys** [comment]
> Won't there still be deprecation notices in PHP 8.4 because `session.sid_length` is still being used?

Thanks for the heads up. I haven't tested my changes with PHP 8.4 yet; I've only researched and made the updates. I'll look into `session.sid_length` and set up a test environment for PHP 8.4.

**Comment by NielBuys** [comment]
> Won't there still be deprecation notices in PHP 8.4 because `session.sid_length` is still being used?

The `session.sid_length` section of the code was sourced from the pull request (https://github.com/codeigniter4/CodeIgniter4/pull/9139) for CodeIgniter 4, which was referenced in issue https://github.com/bcit-ci/CodeIgniter/issues/6300.

**Comment by jamieburchell** [comment]
> The `session.sid_length` section of the code was sourced from the pull request ([codeigniter4/CodeIgniter4#9139](https://github.com/codeigniter4/CodeIgniter4/pull/9139)) for CodeIgniter 4, which was referenced in issue [bcit-ci#6300](https://github.com/bcit-ci/CodeIgniter/issues/6300).

Yup, that forces the params for <PHP9, but it will still trigger a deprecation error. CI4 [gets around that in a different way](https://github.com/codeigniter4/CodeIgniter4/pull/9139/commits/973e1487563b67955e2697d1bf26ec6e8c27824a)

**Comment by jamieburchell** [comment]
At this point and assuming it stops the deprecation notice, I think I'd be tempted to simply prefix the `ini_set` call for `session.sid_length` and `session.sid_bits_per_character` with the error suppression character '@'.

**Comment by NielBuys** [comment]
> At this point and assuming it stops the deprecation notice, I think I'd be tempted to simply prefix the `ini_set` call for `session.sid_length` and `session.sid_bits_per_character` with the error suppression character '@'.

After reviewing it, I believe you're right; it will still trigger the deprecation notice. I think it’s a good idea to add the @ symbol in front of ini_set. I will make that change and then test to see if it works.

**Comment by jamieburchell** [comment]
@NielBuys I was feeling brave and decided to go all-out in my branch and [remove code supporting < PHP 7.4](https://github.com/ib3ltd/CodeIgniter/commit/58bf395d61d30bf77cdbe2a5cc3e4ff382c08921#diff-76c3a452e691f0d0f32375369178c5c2eef8cc7e5c925396aceff1f802d702a7). It might benefit you and your repo. Comments welcome too!

**Comment by NielBuys** [comment]
> @NielBuys I was feeling brave and decided to go all-out in my branch and [remove code supporting < PHP 7.4](https://github.com/ib3ltd/CodeIgniter/commit/58bf395d61d30bf77cdbe2a5cc3e4ff382c08921#diff-76c3a452e691f0d0f32375369178c5c2eef8cc7e5c925396aceff1f802d702a7). It might benefit you and your repo. Comments welcome too!

Thanks, I agree that it's a good idea to clean up some of the older PHP version code. I've created a patch file from your commit and will review it. I’ll let you know if I encounter any issues.

**Comment by rhickmott** [comment]
> Should probably bump the required PHP version to 7.1 if using nullable types. I personally don't care about anything < PHP 8.2, but I'm not sure if these PRs are supposed to be compatible with the PHP version mentioned in composer.json.


It can still be backwards compatible. I don't think there's really that many nullable types in Code Ignitor but this error can be removed by removing the types from the very few functions that use them to maintain backwards compatibility. 
Optionally where needed, a check can be made in code to validate or cast to the required typing or check for nulls. 


> Won't there still be deprecation notices in PHP 8.4 because `session.sid_length` is still being used?

Only if you directly try to set these parameters using ini_set. 
You can check the version for PHP easily in the offending method. 
The code "being there" isn't the problem unless it's a function being removed and then you an add in a dummy function if it doesen't exist in the base language.

elseif( PHP_VERSION_ID >= 80400 ) {
	#PHP 8.4 REMOVES SETTING OF BIRS PER CHARACTER AND SESSION LENGTH
	$bits_per_character		= 	4;
	$sid_length         	= 	32;
}

There is already code in system\librarys\Session\Session for handling legacy versions prior to 7.0.1 in this manor.

The above are the defaults for the session ID which have been 32 Character SSID ( 160bit ) since at least PHP 7.0.1 judging by the code. It looks like the plan it to enforce this default going forward and by the comments it looks like CI was happy with this setting.

// Add as many more characters as necessary to reach at least 160 bits

**Pull request merged**
